esp_toml_version = 1.0

firmware_images_url = "https://misternegative21.github.io/esp_custom_firmwares/"

supported_apps = ["Smart_Shoe_Telegram_Bot"]

[Smart_Shoe_Telegram_Bot]
# ESP32 Chipsets for which you have a supported Firmware App. Define a property for each supported chipset in the given format.
chipsets = ["ESP32"]
# Configure the name of the binary file
image.esp32 = "SoS_Consentium.ino.bootloader"


