esp_toml_version = 1.0

# This should be a publicly accessible URL of the file server where your firmware binaries are available for download
firmware_images_url = "https://github.com/MISTERNEGATIVE21/Smart_Shoe_Bot/blob/master/SoS_Consentium/build/esp32.esp32.esp32doit-devkit-v1/"

# Apps that you support and for which the binaries are available to publish. You can have multiple apps as a comma separated list
# The launch pad UI will automatically show these Apps in the available apps dropdown
# There should be a config section per listed App
supported_apps = ["Smart_Shoe_Bot_Expo_App"]


[Smart_Shoe_Telegram_Bot]
# ESP32 Chipsets for which you have a supported Firmware App. Define a property for each supported chipset in the given format.
chipsets = ["ESP32"]
# Configure the name of the binary file
image.esp32 = "SINGLE_BIN_FOR_ESP32.bin"
# Optional: Phone APP URLs if any for Playstores
android_app_url = ""
ios_app_url = ""
# Optional: URL of the Markdown file for additional information about the app
readme.text = "<URL to your Markdown file>"
# Optional: Supported console baudrate for app firmware (default value is 115200)
console_baudrate = <SUPPORTED_CONSOLE_BAUDRATE>
